# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GQuest(object):
    def setupUi(self, GQuest):
        GQuest.setObjectName("GQuest")
        GQuest.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(GQuest)
        self.centralwidget.setObjectName("centralwidget")
        GQuest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GQuest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        GQuest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GQuest)
        self.statusbar.setObjectName("statusbar")
        GQuest.setStatusBar(self.statusbar)

        self.retranslateUi(GQuest)
        QtCore.QMetaObject.connectSlotsByName(GQuest)

    def retranslateUi(self, GQuest):
        _translate = QtCore.QCoreApplication.translate
        GQuest.setWindowTitle(_translate("GQuest", "MainWindow"))
